Repository billilge/backend, pull requests merged in 2025-02, with the labels that each got.

#61 feat: kotlin-logging을 활용한 로깅 추가
  build.gradle.kts
  src/main/kotlin/site/billilge/api/backend/global/logging/LoggingFilter.kt
Labels: new feature

#64 release: 0.0.3 배포
  build.gradle.kts
  src/main/kotlin/site/billilge/api/backend/domain/item/controller/AdminItemApi.kt
  src/main/kotlin/site/billilge/api/backend/global/logging/LoggingFilter.kt
Labels: release

#65 feat: 알림 조회, 읽음 API 구현
  src/main/kotlin/site/billilge/api/backend/domain/notification/controller/NotificationApi.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/controller/NotificationController.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/dto/response/NotificationDetail.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/dto/response/NotificationFindAllResponse.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/entitiy/Notification.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/enums/NotificationType.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/exception/NotificationErrorCode.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/repository/NotificationRepository.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/service/NotificationService.kt
Labels: new feature

#66 feat: FCM 푸시 알림 세팅 및 구현
  .github/workflows/ci-cd.yml
  build.gradle.kts
  src/main/kotlin/site/billilge/api/backend/domain/member/controller/MemberApi.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/controller/MemberController.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/dto/request/MemberFCMTokenRequest.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/entity/Member.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/service/MemberService.kt
  src/main/kotlin/site/billilge/api/backend/global/external/fcm/FCMConfig.kt
  src/main/kotlin/site/billilge/api/backend/global/external/fcm/FCMService.kt
Labels: new feature, setting

#69 fea: 관리자 알림 API 구현 및 알림 DB 컬럼 수정
  .gitignore
  src/main/kotlin/site/billilge/api/backend/domain/member/repository/MemberRepository.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/controller/AdminNotificationApi.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/controller/AdminNotificationController.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/controller/NotificationApi.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/controller/NotificationController.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/dto/response/NotificationCountResponse.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/dto/response/NotificationDetail.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/dto/response/NotificationFindAllResponse.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/entity/Notification.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/enums/NotificationStatus.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/enums/NotificationType.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/repository/NotificationRepository.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/repository/NotificationRepositoryCustom.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/repository/NotificationRepositoryCustomImpl.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/service/NotificationService.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/enums/RentalStatus.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/service/RentalService.kt
Labels: refactoring, new feature

#70 feat: 대여 물품 검색 조회 API 구현
  src/main/kotlin/site/billilge/api/backend/domain/item/controller/ItemApi.kt
  src/main/kotlin/site/billilge/api/backend/domain/item/controller/ItemController.kt
  src/main/kotlin/site/billilge/api/backend/domain/item/dto/response/ItemDetail.kt
  src/main/kotlin/site/billilge/api/backend/domain/item/repository/ItemRepository.kt
  src/main/kotlin/site/billilge/api/backend/domain/item/service/ItemService.kt
  src/main/kotlin/site/billilge/api/backend/global/dto/SearchCondition.kt
Labels: new feature

#71 release: 0.1.0 배포
  .github/workflows/ci-cd.yml
  .gitignore
  build.gradle.kts
  src/main/kotlin/site/billilge/api/backend/domain/item/controller/ItemApi.kt
  src/main/kotlin/site/billilge/api/backend/domain/item/controller/ItemController.kt
  src/main/kotlin/site/billilge/api/backend/domain/item/dto/response/ItemDetail.kt
  src/main/kotlin/site/billilge/api/backend/domain/item/repository/ItemRepository.kt
  src/main/kotlin/site/billilge/api/backend/domain/item/service/ItemService.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/controller/MemberApi.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/controller/MemberController.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/dto/request/MemberFCMTokenRequest.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/entity/Member.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/repository/MemberRepository.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/service/MemberService.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/controller/AdminNotificationApi.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/controller/AdminNotificationController.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/controller/NotificationApi.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/controller/NotificationController.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/dto/response/NotificationCountResponse.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/dto/response/NotificationDetail.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/dto/response/NotificationFindAllResponse.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/entity/Notification.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/enums/NotificationStatus.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/exception/NotificationErrorCode.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/repository/NotificationRepository.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/repository/NotificationRepositoryCustom.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/repository/NotificationRepositoryCustomImpl.kt
  src/main/kotlin/site/billilge/api/backend/domain/notification/service/NotificationService.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/enums/RentalStatus.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/service/RentalService.kt
  src/main/kotlin/site/billilge/api/backend/global/dto/SearchCondition.kt
  src/main/kotlin/site/billilge/api/backend/global/external/fcm/FCMConfig.kt
  src/main/kotlin/site/billilge/api/backend/global/external/fcm/FCMService.kt
Labels: release

#72 HOTFIX: 대여 시간 관련 예외처리 임시 주석처리
  src/main/kotlin/site/billilge/api/backend/domain/rental/service/RentalService.kt
Labels: bug

#73 release: 0.1.0 배포
  src/main/kotlin/site/billilge/api/backend/domain/item/entity/Item.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/exception/RentalErrorCode.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/service/RentalService.kt
Labels: release

#75 fix: 대여 내역에 빌린 물품 개수 정보 추가
  src/main/kotlin/site/billilge/api/backend/domain/rental/controller/AdminRentalApi.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/controller/AdminRentalController.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/entity/RentalHistory.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/service/RentalService.kt
Labels: bug

#76 release: 0.1.1 배포
  src/main/kotlin/site/billilge/api/backend/domain/rental/controller/AdminRentalApi.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/controller/AdminRentalController.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/entity/RentalHistory.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/service/RentalService.kt
Labels: release

#77 HOTFIX: 대여 상태를 변경한 관리자 id를 넘겨주지 않아 생긴 오류 수정
  src/main/kotlin/site/billilge/api/backend/domain/rental/controller/AdminRentalController.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/entity/RentalHistory.kt
  src/main/kotlin/site/billilge/api/backend/domain/rental/service/RentalService.kt
Labels: bug, release

#78 release: 토큰에 회원 이름 정보 추가
  src/main/kotlin/site/billilge/api/backend/global/security/jwt/TokenProvider.kt
Labels: new feature, release

#80 fix: 대여 승인 시에 물품 수량이 없다면 승인되지 않도록 수정 완료
  src/main/kotlin/site/billilge/api/backend/domain/rental/service/RentalService.kt
Labels: bug

#82 feat: 관리자 로그인 API 구현
  src/main/kotlin/site/billilge/api/backend/domain/member/controller/AuthApi.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/controller/AuthController.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/dto/request/AdminLoginRequest.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/dto/response/AdminLoginResponse.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/exception/MemberErrorCode.kt
  src/main/kotlin/site/billilge/api/backend/domain/member/service/MemberService.kt
  src/main/resources/application-prod.yml
Labels: new feature

#84 fix: 알림 개수 API 호출 시 읽지 않은 알림 개수로 보내도록 수정
  src/main/kotlin/site/billilge/api/backend/domain/notification/repository/NotificationRepositoryCustomImpl.kt
Labels: bug
